
export const KANJI_DATA = [
  { kanji: '力', meaning: 'Power' },
  { kanji: '火', meaning: 'Fire' },
  { kanji: '水', meaning: 'Water' },
  { kanji: '風', meaning: 'Wind' },
  { kanji: '土', meaning: 'Earth' },
  { kanji: '空', meaning: 'Sky/Void' },
  { kanji: '天', meaning: 'Heaven' },
  { kanji: '地', meaning: 'Earth' },
  { kanji: '龍', meaning: 'Dragon' },
  { kanji: '虎', meaning: 'Tiger' },
  { kanji: '狼', meaning: 'Wolf' },
  { kanji: '侍', meaning: 'Samurai' },
  { kanji: '忍', meaning: 'Ninja' },
  { kanji: '影', meaning: 'Shadow' },
  { kanji: '光', meaning: 'Light' },
  { kanji: '闇', meaning: 'Darkness' },
  { kanji: '鬼', meaning: 'Demon' },
  { kanji: '神', meaning: 'God' },
  { kanji: '魂', meaning: 'Soul' },
  { kanji: '心', meaning: 'Heart' },
  { kanji: '剣', meaning: 'Sword' },
  { kanji: '刃', meaning: 'Blade' },
  { kanji: '道', meaning: 'Way/Path' },
  { kanji: '武', meaning: 'Martial' },
  { kanji: '士', meaning: 'Warrior' },
  { kanji: '王', meaning: 'King' },
  { kanji: '皇', meaning: 'Emperor' },
  { kanji: '月', meaning: 'Moon' },
  { kanji: '日', meaning: 'Sun' },
  { kanji: '星', meaning: 'Star' },
  { kanji: '花', meaning: 'Flower' },
  { kanji: '桜', meaning: 'Cherry Blossom' },
  { kanji: '山', meaning: 'Mountain' },
  { kanji: '川', meaning: 'River' },
  { kanji: '海', meaning: 'Sea' },
  { kanji: '森', meaning: 'Forest' },
  { kanji: '木', meaning: 'Tree' },
  { kanji: '金', meaning: 'Gold' },
  { kanji: '銀', meaning: 'Silver' },
  { kanji: '鉄', meaning: 'Iron' },
];
